variable "vmss_name" {}
variable "starting_instance_count" {}
variable "vmss_admin_username" {}
variable "vmss_admin_password" {}
variable "nic_name" {}
variable "rg_name" {}
variable "vnet_name" {}
variable "subnet_name" {}
variable "os_publisher" {}
variable "os_offer" {}
variable "os_sku" {}
variable "os_version" {}
variable "vm_increase_threshold" {}
variable "vm_decrease_threshold" {}
variable "vm_increase_count" {}
variable "vm_decrease_count" {}
variable "lb_name" {}
variable "lb_backend_pool_name" {}
variable "vm_count_min" {}
variable "vm_count_max" {}
variable "vm_count_default" {}